/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as AuthorizedAppsRouteImport } from './routes/authorized-apps'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HumanVerificationRouteImport } from './routes/human-verification'
import { Route as IdentityVerificationRouteImport } from './routes/identity-verification'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as DeveloperDemoRouteImport } from './routes/developer/demo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizedAppsRoute = AuthorizedAppsRouteImport.update({
  id: '/authorized-apps',
  path: '/authorized-apps',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HumanVerificationRoute = HumanVerificationRouteImport.update({
  id: '/human-verification',
  path: '/human-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityVerificationRoute = IdentityVerificationRouteImport.update({
  id: '/identity-verification',
  path: '/identity-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDemoRoute = DeveloperDemoRouteImport.update({
  id: '/developer/demo',
  path: '/developer/demo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/authorized-apps': typeof AuthorizedAppsRoute
  '/dashboard': typeof DashboardRoute
  '/human-verification': typeof HumanVerificationRoute
  '/identity-verification': typeof IdentityVerificationRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/developer/demo': typeof DeveloperDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/authorized-apps': typeof AuthorizedAppsRoute
  '/dashboard': typeof DashboardRoute
  '/human-verification': typeof HumanVerificationRoute
  '/identity-verification': typeof IdentityVerificationRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/developer/demo': typeof DeveloperDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authorize': typeof AuthorizeRoute
  '/authorized-apps': typeof AuthorizedAppsRoute
  '/dashboard': typeof DashboardRoute
  '/human-verification': typeof HumanVerificationRoute
  '/identity-verification': typeof IdentityVerificationRoute
  '/inbox': typeof InboxRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/developer/demo': typeof DeveloperDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/authorized-apps'
    | '/dashboard'
    | '/human-verification'
    | '/identity-verification'
    | '/inbox'
    | '/profile'
    | '/settings'
    | '/verify'
    | '/developer/demo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/authorized-apps'
    | '/dashboard'
    | '/human-verification'
    | '/identity-verification'
    | '/inbox'
    | '/profile'
    | '/settings'
    | '/verify'
    | '/developer/demo'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/authorized-apps'
    | '/dashboard'
    | '/human-verification'
    | '/identity-verification'
    | '/inbox'
    | '/profile'
    | '/settings'
    | '/verify'
    | '/developer/demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorizeRoute: typeof AuthorizeRoute
  AuthorizedAppsRoute: typeof AuthorizedAppsRoute
  DashboardRoute: typeof DashboardRoute
  HumanVerificationRoute: typeof HumanVerificationRoute
  IdentityVerificationRoute: typeof IdentityVerificationRoute
  InboxRoute: typeof InboxRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  VerifyRoute: typeof VerifyRoute
  DeveloperDemoRoute: typeof DeveloperDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorized-apps': {
      id: '/authorized-apps'
      path: '/authorized-apps'
      fullPath: '/authorized-apps'
      preLoaderRoute: typeof AuthorizedAppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/human-verification': {
      id: '/human-verification'
      path: '/human-verification'
      fullPath: '/human-verification'
      preLoaderRoute: typeof HumanVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity-verification': {
      id: '/identity-verification'
      path: '/identity-verification'
      fullPath: '/identity-verification'
      preLoaderRoute: typeof IdentityVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/demo': {
      id: '/developer/demo'
      path: '/developer/demo'
      fullPath: '/developer/demo'
      preLoaderRoute: typeof DeveloperDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorizeRoute: AuthorizeRoute,
  AuthorizedAppsRoute: AuthorizedAppsRoute,
  DashboardRoute: DashboardRoute,
  HumanVerificationRoute: HumanVerificationRoute,
  IdentityVerificationRoute: IdentityVerificationRoute,
  InboxRoute: InboxRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  VerifyRoute: VerifyRoute,
  DeveloperDemoRoute: DeveloperDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
